  default: &default
    adapter: postgresql
    encoding: unicode

    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  development:
    <<: *default
    database: forum_development

  test:
    <<: *default
    database: forum_test

  production:
    <<: *default
    database: forum-jm_production
    username: forum-jm
    password: <%= ENV['FORUM-JM_DATABASE_PASSWORD'] %>
